#---
#server: 
#  port: 8081
#  servlet: 
#    context-path: /resource-server
#
#spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8083/auth/realms/baeldung
#          jwk-set-uri: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 482155388371-5dhtikfu6veho3hn3htb5fidq6k19l3t.apps.googleusercontent.com
            clientSecret: rAnIc726A3qhiBvJe26wIeIi
            scope:
            - email
            - profile